### ISSUE TITLE
Add method to compute explained covariance 

### ISSUE THREAD

**Issue by JohannesWiesner** [jameschapman19/cca_zoo#134]
I know this is easy to compute, but still nice to have out-of-the-box: Wouldn't it make sense to also add a `compute_covariance` method to `_CCA_Base`? Like such:

```python
def explained_variance(X,y,X_weights,y_weights):
    '''Compute covariance'''

    # standardize X and y 
    X_std = zscore(X,axis=0,ddof=1)
    y_std = zscore(y,axis=0,ddof=1)
    
    # calculate covariance matrix
    covmat = X_weights.T @ X_std.T @ y_std @ y_weights
    
    # calculate covariance explained by each component
    explained_var =  np.diag(covmat)**2 / np.sum(np.diag(covmat)**2) 

    return explained_var
```

**Comment by jameschapman19** [comment]
Yeah cool idea - would be delighted to accept a PR with essentially what you have described here. Otherwise will take a look in the future when I have some spare time :)

**Comment by jameschapman19** [comment]
Have you got a citation for the calculation?

**Comment by JohannesWiesner** [comment]
Yes, implemented it from [here ](https://github.com/cedricx/sCCA/blob/d5a2f4cb071bddd3f7d805e02ff27828b8494c66/sCCA/code/final/sCCA_pwr.Rmd#L66-L70). Therefore the corresponding citation would be:

DOI: 10.1038/s41467-018-05317-y

**Comment by JohannesWiesner** [comment]
AFAIK this is the explained **co**variance so it does explain how much of the total covariance of X and y can be explained by the covariance of the respective variates.

**Comment by jameschapman19** [comment]
As with all things around these subspace methods I think there is an interesting discussion to be had.

I have actually moved the explained variance out of the BaseModel class (it is available to models with 'PLS' style constraints).

This is because the CCA models in this package are normalized so that the transformed/low-dimensional representation/canonical variates have unit variance in expectation whereas the weights having variance as in PLS style models.

So to compute explained variance for a CCA model you would first need to normalize the weights to unit variance. 

I could add back in the explained variance method with something like a normalized_weights attribute that scales the weights. Something like  the below

```
    def _normalized_weights(self):
        """
        Returns the normalized weights

        Returns
        -------
        normalized_weights : list of numpy arrays

        """
        return [w / np.linalg.norm(w, axis=0) for w in self.weights]
```

**Comment by jameschapman19** [comment]
In fact this strikes me as a good idea.

**Comment by WantongLi123** [comment]
Hey James, happy to catch you online. i try to calculate explained variance ratio for MCCA, multiple views, straggling for a day and failed. ANY chance that you incorporate that function code?

**Comment by jameschapman19** [comment]
Have now added in explained_variance, explained_variance_ratio, explained_variance_cumulative as well as explained_covariance, explained_covariance_ratio, explained_covariance_cumulative.

This has been achieved by adding a new class attribute 'loadings' which are normalized weights which are equivalent to PCA loadings ie ||w||=1 and w=loadings.

I have renamed factor_loadings to canonical loadings following stackoverflow discussion while recognising the confusion that exists in the literature.

**Comment by jameschapman19** [comment]
Thanks for the encouragement to fix this up @WantongLi123! It's a nice change that I think has a lot of value in post-hoc analysis of these kind of models.
