### ISSUE TITLE
The p-value of "cca_zoo.models.SCCA_PMD.pairwise_correlations"

### ISSUE THREAD

**Issue by xiluwang** [jameschapman19/cca_zoo#146]
Is there a way to get the p-value corresponding to the method "cca_zoo.models.SCCA_PMD.pairwise_correlations"?

**Comment by jameschapman19** [comment]
Hi @xiluwang! I set up the permutation_test_score() function after #124 which works for one latent dimension (and basically just sets up a pipeline to the scikit-learn permutation_test_score() so it's fast/reliable.

To get separate p-values for each latent dimension would take some fiddling because scikit-learn's scorers expect a scalar output so in its current form permutation_test_score() will average all of the latent dimensions.

**Comment by xiluwang** [comment]
Hi James! Thanks for the reply, when I input more than 2 views, using "permutation_test_score" can only get one average p-value. Is it possible to output the p-value between every 2 views when input more than 2 views? Or can only be calculated separately when using 2 views?

**Comment by jameschapman19** [comment]
@xiluwang I've changed the way permuation_test_score() works so that for 2 views it by default returns p values for each dimension and for >2 views it refers p values for each of the (#views,#views,#dimensions) output of pairwise_correlations()
