### ISSUE TITLE
examples with gpu?

### ISSUE THREAD

**Issue by brando90** [jameschapman19/cca_zoo#2]
are there examples with gpus?

**Comment by jameschapman19** [comment]
Hi Brando - I'm working on improving my commenting/documentation across the board and will make sure to make GPU support obvious. 

I _think_ that the wrapped models that I put in the example will work with GPU since they use:

`self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`

and associated

`.to(device)` 

on both the models and data in training this should work out of the box if your machine has GPU available.

**Comment by jameschapman19** [comment]
I'm now able to test the gpu methods locally and satisfied that they work as expected - therefore closing.
