### ISSUE TITLE
Replace assertion with exception 

### ISSUE THREAD

**Issue by htwangtw** [jameschapman19/cca_zoo#21]
Hi, thanks for creating this super useful project!
I noticed you used assertion for error catching in the modules.
It would be clearer for the user if these are handled with exceptions and improve the error message.
Let me know if you think this is a good idea. Happy to work on a PR for this.

**Comment by jameschapman19** [comment]
Hi @htwangtw,

Thanks very much!

I'd be more than happy to accept a PR and acknowledge it. There should be some easy ones like you say where I've written the assertion but not written a helpful exception e.g. PMD has regularisation 1<c<sqrt(#features) to ensure that both L1 and L2 constraints are active. Happy to answer any questions on any of these.

There's others where I've been intending to add assertions/exceptions but need to have a think about what they are - e.g. DCCA is typically only stable for batch size > latent dimensions. If there's any obvious ones then again happy to accept them.

If you do a PR (or otherwise) and in the process spot anything that looks odd give me a shout!

**Comment by htwangtw** [comment]
I am modifying the existing assertions for now! It would be great for you to have a look.
